version: '2'
services:
  smartdns:
    container_name: smartdns
    hostname: smartdns
    image: yangliu/smartdns
    ports:
      - "53:53/udp"
    environment:
      - PUID=1000
      - PGID=1000
    restart: always
    volumes:
      - /docker/smartdns:/config
